<a href="https://colab.research.google.com/github/amnasyed1/datasci_2_manipulation/blob/main/week2assignment507.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Assignment 2- Data Cleaning and Preprocessing**

In [4]:
import pandas as pd
import re
import numpy as np

## Data Cleaning with Pandas

In [6]:
hcdata = pd.read_csv("https://raw.githubusercontent.com/hantswilliams/HHA_507_2023/main/WK2/data/healthcare_data_cleaning.csv", na_values=["missing"])
hcdata

,Patient Age,Gender,City of Residence,State of Residence,Has Insurance,Visited Last Month,Payment Method,Preferred Doctor,Disease Diagnosed,Medication Prescribed,Type of Appointment,Average Heart Rate,Average BP,Height (in cm),Weight (in kg),Payment Due ($),Last Visit (days ago),Visit Duration (mins),Number of Tests,Prescription Cost ($)
0,45.0,Other,West Brian,Kentucky,Yes,Yes,Insurance,Dr. Williams,Flu,Med_E,General,66.0,111.0,183.0,70.0,65.457216,193.0,92.0,5.0,15.717517
1,25.0,Female,East Jocelynfurt,Colorado,No,Yes,Card,Dr. Johnson,Flu,Med_B,Specialist,59.0,NaN,174.0,58.0,430.683657,195.0,NaN,4.0,80.786473
2,51.0,Other,South Lindseyland,Ohio,Yes,No,Cash,Dr. Williams,Covid-19,Med_D,General,79.0,119.0,161.0,56.0,315.070931,NaN,37.0,2.0,64.392139
3,18.0,Female,Taylorfort,Pennsylvania,Yes,NaN,Cash,Dr. Williams,Flu,Med_A,General,99.0,115.0,171.0,52.0,320.299899,175.0,108.0,2.0,8.872859
4,48.0,Female,Birdmouth,Montana,No,No,Insurance,Dr. Brown,None,Med_C,Specialist,93.0,89.0,186.0,87.0,264.214737,188.0,113.0,3.0,77.483113
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
104995,74.0,Other,West Anthony,Oklahoma,Yes,No,Card,Dr. Williams,Covid-19,Med_E,Specialist,65.0,112.0,169.0,61.0,309.164446,183.0,10.0,3.0,63.204788
104996,37.0,Male,Mckeetown,Utah,Yes,No,Cash,Dr. Jones,Covid-19,Med_C,General,NaN,111.0,165.0,67.0,NaN,191.0,47.0,2.0,113.867640
104997,51.0,Female,Lake Lisachester,Nebraska,Yes,Yes,Insurance,Dr. Williams,Allergy,Med_D,Follow-Up,89.0,118.0,179.0,71.0,320.830418,172.0,39.0,3.0,35.622420
104998,NaN,Female,Heidiborough,NaN,Yes,No,Cash,Dr. Smith,Covid-19,Med_A,Follow-Up,74.0,123.0,167.0,75.0,5.341231,180.0,79.0,NaN,124.408341
104999,45.0,Female,South Jeffrey,Massachusetts,No,Yes,Cash,Dr. Brown,Allergy,Med_D,General,77.0,140.0,167.0,62.0,454.949839,167.0,81.0,NaN,87.910601

#### Data Shape, Size

In [87]:
print ("Number of rows:", hcdata.shape[0])
print ("Number of columns:", hcdata.shape[1])

Number of rows: 37594
Number of columns: 23

In [89]:
print ("Using size:", hcdata.shape)

Using size: (37594, 23)

In [88]:
print ("Using size:" , hcdata.size)

Using size: 864662

## Indentifying and Handling the Missing Values in the Dataset

  - After that used the data.fillna function to fill in the missing values as NaN (Not a Number), which I also used when loading the CSV file to indicate where in the dataset there were missing values that were expressed by "missing"

In [7]:
missing_values = hcdata.isnull()
all_missing_values = missing_values.sum() .sum()
print(all_missing_values)

105001

In [8]:
missing_values = hcdata.fillna(np.nan)
missing_values

,Patient Age,Gender,City of Residence,State of Residence,Has Insurance,Visited Last Month,Payment Method,Preferred Doctor,Disease Diagnosed,Medication Prescribed,Type of Appointment,Average Heart Rate,Average BP,Height (in cm),Weight (in kg),Payment Due ($),Last Visit (days ago),Visit Duration (mins),Number of Tests,Prescription Cost ($)
0,45.0,Other,West Brian,Kentucky,Yes,Yes,Insurance,Dr. Williams,Flu,Med_E,General,66.0,111.0,183.0,70.0,65.457216,193.0,92.0,5.0,15.717517
1,25.0,Female,East Jocelynfurt,Colorado,No,Yes,Card,Dr. Johnson,Flu,Med_B,Specialist,59.0,NaN,174.0,58.0,430.683657,195.0,NaN,4.0,80.786473
2,51.0,Other,South Lindseyland,Ohio,Yes,No,Cash,Dr. Williams,Covid-19,Med_D,General,79.0,119.0,161.0,56.0,315.070931,NaN,37.0,2.0,64.392139
3,18.0,Female,Taylorfort,Pennsylvania,Yes,NaN,Cash,Dr. Williams,Flu,Med_A,General,99.0,115.0,171.0,52.0,320.299899,175.0,108.0,2.0,8.872859
4,48.0,Female,Birdmouth,Montana,No,No,Insurance,Dr. Brown,None,Med_C,Specialist,93.0,89.0,186.0,87.0,264.214737,188.0,113.0,3.0,77.483113
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
104995,74.0,Other,West Anthony,Oklahoma,Yes,No,Card,Dr. Williams,Covid-19,Med_E,Specialist,65.0,112.0,169.0,61.0,309.164446,183.0,10.0,3.0,63.204788
104996,37.0,Male,Mckeetown,Utah,Yes,No,Cash,Dr. Jones,Covid-19,Med_C,General,NaN,111.0,165.0,67.0,NaN,191.0,47.0,2.0,113.867640
104997,51.0,Female,Lake Lisachester,Nebraska,Yes,Yes,Insurance,Dr. Williams,Allergy,Med_D,Follow-Up,89.0,118.0,179.0,71.0,320.830418,172.0,39.0,3.0,35.622420
104998,NaN,Female,Heidiborough,NaN,Yes,No,Cash,Dr. Smith,Covid-19,Med_A,Follow-Up,74.0,123.0,167.0,75.0,5.341231,180.0,79.0,NaN,124.408341
104999,45.0,Female,South Jeffrey,Massachusetts,No,Yes,Cash,Dr. Brown,Allergy,Med_D,General,77.0,140.0,167.0,62.0,454.949839,167.0,81.0,NaN,87.910601

### Removing Duplicate Rows and Columns/ Cleaning Columns

  - I removed duplicate rows by using the .dropna(inplace = True) function
  - I removed the duplicate columns by using the .loc [:, ~hcdata.columns.duplicated()] function. The source I used to help me with this function was https://sparkbyexamples.com/pandas/pandas-remove-duplicate-columns-from-dataframe/
  - To clean the columns names I used hcdata.columns = hcdata.columns.str.strip()
  - Additionally, to clean the columns I used the clean_value function to remove any white space from the columns

In [9]:
hcdata.dropna(inplace = True)
hcdata

,Patient Age,Gender,City of Residence,State of Residence,Has Insurance,Visited Last Month,Payment Method,Preferred Doctor,Disease Diagnosed,Medication Prescribed,Type of Appointment,Average Heart Rate,Average BP,Height (in cm),Weight (in kg),Payment Due ($),Last Visit (days ago),Visit Duration (mins),Number of Tests,Prescription Cost ($)
0,45.0,Other,West Brian,Kentucky,Yes,Yes,Insurance,Dr. Williams,Flu,Med_E,General,66.0,111.0,183.0,70.0,65.457216,193.0,92.0,5.0,15.717517
4,48.0,Female,Birdmouth,Montana,No,No,Insurance,Dr. Brown,None,Med_C,Specialist,93.0,89.0,186.0,87.0,264.214737,188.0,113.0,3.0,77.483113
7,52.0,Male,Vanessaburgh,Connecticut,Yes,Yes,Insurance,Dr. Williams,Flu,Med_E,General,99.0,129.0,170.0,47.0,387.085044,179.0,108.0,2.0,76.965926
8,20.0,Female,West Briannabury,Montana,No,Yes,Card,Dr. Jones,Flu,Med_C,Specialist,67.0,108.0,173.0,86.0,172.548343,174.0,91.0,2.0,142.317108
11,40.0,Female,Jonesmouth,Rhode Island,No,No,Card,Dr. Jones,Covid-19,Med_E,Specialist,65.0,106.0,166.0,82.0,299.142676,193.0,92.0,1.0,77.715360
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
104992,44.0,Female,Port Tracistad,Alaska,Yes,No,Insurance,Dr. Brown,Cold,Med_A,Follow-Up,76.0,93.0,178.0,66.0,462.565671,189.0,55.0,3.0,59.746318
104993,42.0,Female,West Annaport,Florida,Yes,No,Cash,Dr. Johnson,Covid-19,Med_D,Specialist,80.0,129.0,171.0,78.0,131.356326,185.0,22.0,6.0,104.430167
104994,53.0,Female,Michelleburgh,South Dakota,No,No,Card,Dr. Williams,Flu,Med_B,Emergency,68.0,109.0,172.0,75.0,488.031604,167.0,25.0,5.0,69.542286
104995,74.0,Other,West Anthony,Oklahoma,Yes,No,Card,Dr. Williams,Covid-19,Med_E,Specialist,65.0,112.0,169.0,61.0,309.164446,183.0,10.0,3.0,63.204788
104997,51.0,Female,Lake Lisachester,Nebraska,Yes,Yes,Insurance,Dr. Williams,Allergy,Med_D,Follow-Up,89.0,118.0,179.0,71.0,320.830418,172.0,39.0,3.0,35.622420

In [17]:
hcdata = hcdata.loc [:, ~hcdata.columns.duplicated()]
hcdata

,patientage,gender,cityofresidence,stateofresidence,hasinsurance,visitedlastmonth,paymentmethod,preferreddoctor,diseasediagnosed,medicationprescribed,typeofappointment,averageheartrate,averagebp,heightincm,weightinkg,paymentdue,lastvisitdaysago,visitdurationmins,numberoftests,prescriptioncost
0,45.0,Other,West Brian,Kentucky,Yes,Yes,Insurance,Dr. Williams,Flu,Med_E,General,66.0,111.0,183.0,70.0,65.457216,193.0,92.0,5.0,15.717517
4,48.0,Female,Birdmouth,Montana,No,No,Insurance,Dr. Brown,None,Med_C,Specialist,93.0,89.0,186.0,87.0,264.214737,188.0,113.0,3.0,77.483113
7,52.0,Male,Vanessaburgh,Connecticut,Yes,Yes,Insurance,Dr. Williams,Flu,Med_E,General,99.0,129.0,170.0,47.0,387.085044,179.0,108.0,2.0,76.965926
8,20.0,Female,West Briannabury,Montana,No,Yes,Card,Dr. Jones,Flu,Med_C,Specialist,67.0,108.0,173.0,86.0,172.548343,174.0,91.0,2.0,142.317108
11,40.0,Female,Jonesmouth,Rhode Island,No,No,Card,Dr. Jones,Covid-19,Med_E,Specialist,65.0,106.0,166.0,82.0,299.142676,193.0,92.0,1.0,77.715360
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
104992,44.0,Female,Port Tracistad,Alaska,Yes,No,Insurance,Dr. Brown,Cold,Med_A,Follow-Up,76.0,93.0,178.0,66.0,462.565671,189.0,55.0,3.0,59.746318
104993,42.0,Female,West Annaport,Florida,Yes,No,Cash,Dr. Johnson,Covid-19,Med_D,Specialist,80.0,129.0,171.0,78.0,131.356326,185.0,22.0,6.0,104.430167
104994,53.0,Female,Michelleburgh,South Dakota,No,No,Card,Dr. Williams,Flu,Med_B,Emergency,68.0,109.0,172.0,75.0,488.031604,167.0,25.0,5.0,69.542286
104995,74.0,Other,West Anthony,Oklahoma,Yes,No,Card,Dr. Williams,Covid-19,Med_E,Specialist,65.0,112.0,169.0,61.0,309.164446,183.0,10.0,3.0,63.204788
104997,51.0,Female,Lake Lisachester,Nebraska,Yes,Yes,Insurance,Dr. Williams,Allergy,Med_D,Follow-Up,89.0,118.0,179.0,71.0,320.830418,172.0,39.0,3.0,35.622420

In [13]:
hcdata.columns = hcdata.columns.str.strip()
hcdata

,Patient Age,Gender,City of Residence,State of Residence,Has Insurance,Visited Last Month,Payment Method,Preferred Doctor,Disease Diagnosed,Medication Prescribed,Type of Appointment,Average Heart Rate,Average BP,Height (in cm),Weight (in kg),Payment Due ($),Last Visit (days ago),Visit Duration (mins),Number of Tests,Prescription Cost ($)
0,45.0,Other,West Brian,Kentucky,Yes,Yes,Insurance,Dr. Williams,Flu,Med_E,General,66.0,111.0,183.0,70.0,65.457216,193.0,92.0,5.0,15.717517
4,48.0,Female,Birdmouth,Montana,No,No,Insurance,Dr. Brown,None,Med_C,Specialist,93.0,89.0,186.0,87.0,264.214737,188.0,113.0,3.0,77.483113
7,52.0,Male,Vanessaburgh,Connecticut,Yes,Yes,Insurance,Dr. Williams,Flu,Med_E,General,99.0,129.0,170.0,47.0,387.085044,179.0,108.0,2.0,76.965926
8,20.0,Female,West Briannabury,Montana,No,Yes,Card,Dr. Jones,Flu,Med_C,Specialist,67.0,108.0,173.0,86.0,172.548343,174.0,91.0,2.0,142.317108
11,40.0,Female,Jonesmouth,Rhode Island,No,No,Card,Dr. Jones,Covid-19,Med_E,Specialist,65.0,106.0,166.0,82.0,299.142676,193.0,92.0,1.0,77.715360
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
104992,44.0,Female,Port Tracistad,Alaska,Yes,No,Insurance,Dr. Brown,Cold,Med_A,Follow-Up,76.0,93.0,178.0,66.0,462.565671,189.0,55.0,3.0,59.746318
104993,42.0,Female,West Annaport,Florida,Yes,No,Cash,Dr. Johnson,Covid-19,Med_D,Specialist,80.0,129.0,171.0,78.0,131.356326,185.0,22.0,6.0,104.430167
104994,53.0,Female,Michelleburgh,South Dakota,No,No,Card,Dr. Williams,Flu,Med_B,Emergency,68.0,109.0,172.0,75.0,488.031604,167.0,25.0,5.0,69.542286
104995,74.0,Other,West Anthony,Oklahoma,Yes,No,Card,Dr. Williams,Covid-19,Med_E,Specialist,65.0,112.0,169.0,61.0,309.164446,183.0,10.0,3.0,63.204788
104997,51.0,Female,Lake Lisachester,Nebraska,Yes,Yes,Insurance,Dr. Williams,Allergy,Med_D,Follow-Up,89.0,118.0,179.0,71.0,320.830418,172.0,39.0,3.0,35.622420

In [14]:
# Function to remove white space and special characters from a value
def clean_column_names(hcdata):
    # Define a helper function to clean column names
    def clean_name(value):
        cleaned_name = re.sub(r'[^a-zA-Z0-9]', '', value)
        return cleaned_name.lower()


    hcdata.columns = [clean_name(col) for col in hcdata.columns]
    return hcdata

data = clean_column_names(hcdata)

print(hcdata)

        patientage  gender   cityofresidence stateofresidence hasinsurance  \
0             45.0   Other        West Brian         Kentucky          Yes
4             48.0  Female         Birdmouth          Montana           No
7             52.0    Male      Vanessaburgh      Connecticut          Yes
8             20.0  Female  West Briannabury          Montana           No
11            40.0  Female        Jonesmouth     Rhode Island           No
...            ...     ...               ...              ...          ...
104992        44.0  Female    Port Tracistad           Alaska          Yes
104993        42.0  Female     West Annaport          Florida          Yes
104994        53.0  Female     Michelleburgh     South Dakota           No
104995        74.0   Other      West Anthony         Oklahoma          Yes
104997        51.0  Female  Lake Lisachester         Nebraska          Yes

       visitedlastmonth paymentmethod preferreddoctor diseasediagnosed  \
0                   Yes     Insurance    Dr. Williams              Flu
4                    No     Insurance       Dr. Brown             None
7                   Yes     Insurance    Dr. Williams              Flu
8                   Yes          Card       Dr. Jones              Flu
11                   No          Card       Dr. Jones         Covid-19
...                 ...           ...             ...              ...
104992               No     Insurance       Dr. Brown             Cold
104993               No          Cash     Dr. Johnson         Covid-19
104994               No          Card    Dr. Williams              Flu
104995               No          Card    Dr. Williams         Covid-19
104997              Yes     Insurance    Dr. Williams          Allergy

       medicationprescribed typeofappointment  averageheartrate  averagebp  \
0                     Med_E           General              66.0      111.0
4                     Med_C        Specialist              93.0       89.0
7                     Med_E           General              99.0      129.0
8                     Med_C        Specialist              67.0      108.0
11                    Med_E        Specialist              65.0      106.0
...                     ...               ...               ...        ...
104992                Med_A         Follow-Up              76.0       93.0
104993                Med_D        Specialist              80.0      129.0
104994                Med_B         Emergency              68.0      109.0
104995                Med_E        Specialist              65.0      112.0
104997                Med_D         Follow-Up              89.0      118.0

        heightincm  weightinkg  paymentdue  lastvisitdaysago  \
0            183.0        70.0   65.457216             193.0
4            186.0        87.0  264.214737             188.0
7            170.0        47.0  387.085044             179.0
8            173.0        86.0  172.548343             174.0
11           166.0        82.0  299.142676             193.0
...            ...         ...         ...               ...
104992       178.0        66.0  462.565671             189.0
104993       171.0        78.0  131.356326             185.0
104994       172.0        75.0  488.031604             167.0
104995       169.0        61.0  309.164446             183.0
104997       179.0        71.0  320.830418             172.0

        visitdurationmins  numberoftests  prescriptioncost
0                    92.0            5.0         15.717517
4                   113.0            3.0         77.483113
7                   108.0            2.0         76.965926
8                    91.0            2.0        142.317108
11                   92.0            1.0         77.715360
...                   ...            ...               ...
104992               55.0            3.0         59.746318
104993               22.0            6.0        104.430167
104994               25.0            5.0         69.542286
104995               10.0            3.0         63.204788
104997               39.0            3.0         35.622420

[37594 rows x 20 columns]

In [15]:
hcdata

,patientage,gender,cityofresidence,stateofresidence,hasinsurance,visitedlastmonth,paymentmethod,preferreddoctor,diseasediagnosed,medicationprescribed,typeofappointment,averageheartrate,averagebp,heightincm,weightinkg,paymentdue,lastvisitdaysago,visitdurationmins,numberoftests,prescriptioncost
0,45.0,Other,West Brian,Kentucky,Yes,Yes,Insurance,Dr. Williams,Flu,Med_E,General,66.0,111.0,183.0,70.0,65.457216,193.0,92.0,5.0,15.717517
4,48.0,Female,Birdmouth,Montana,No,No,Insurance,Dr. Brown,None,Med_C,Specialist,93.0,89.0,186.0,87.0,264.214737,188.0,113.0,3.0,77.483113
7,52.0,Male,Vanessaburgh,Connecticut,Yes,Yes,Insurance,Dr. Williams,Flu,Med_E,General,99.0,129.0,170.0,47.0,387.085044,179.0,108.0,2.0,76.965926
8,20.0,Female,West Briannabury,Montana,No,Yes,Card,Dr. Jones,Flu,Med_C,Specialist,67.0,108.0,173.0,86.0,172.548343,174.0,91.0,2.0,142.317108
11,40.0,Female,Jonesmouth,Rhode Island,No,No,Card,Dr. Jones,Covid-19,Med_E,Specialist,65.0,106.0,166.0,82.0,299.142676,193.0,92.0,1.0,77.715360
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
104992,44.0,Female,Port Tracistad,Alaska,Yes,No,Insurance,Dr. Brown,Cold,Med_A,Follow-Up,76.0,93.0,178.0,66.0,462.565671,189.0,55.0,3.0,59.746318
104993,42.0,Female,West Annaport,Florida,Yes,No,Cash,Dr. Johnson,Covid-19,Med_D,Specialist,80.0,129.0,171.0,78.0,131.356326,185.0,22.0,6.0,104.430167
104994,53.0,Female,Michelleburgh,South Dakota,No,No,Card,Dr. Williams,Flu,Med_B,Emergency,68.0,109.0,172.0,75.0,488.031604,167.0,25.0,5.0,69.542286
104995,74.0,Other,West Anthony,Oklahoma,Yes,No,Card,Dr. Williams,Covid-19,Med_E,Specialist,65.0,112.0,169.0,61.0,309.164446,183.0,10.0,3.0,63.204788
104997,51.0,Female,Lake Lisachester,Nebraska,Yes,Yes,Insurance,Dr. Williams,Allergy,Med_D,Follow-Up,89.0,118.0,179.0,71.0,320.830418,172.0,39.0,3.0,35.622420

## Data Transformation

Created new columns based on existing ones.

In [91]:
hcdata = pd.DataFrame(hcdata)

threshold_young = 40

hcdata['patientunder40'] = hcdata['patientage'].apply(lambda x: 'Older' if x >= threshold_young else 'Younger')

print(hcdata[[ 'patientage', 'patientunder40']].head(10))

    patientage patientunder40
0         45.0          Older
4         48.0          Older
7         52.0          Older
8         20.0        Younger
11        40.0          Older
12        34.0        Younger
13        43.0          Older
15        54.0          Older
17        64.0          Older
21        26.0        Younger

### Aggregating Data

  - using groupby
  - using compute summary statistics

In [90]:
hcdata['medicationprescribed'].value_counts()

Med_B    7635
Med_C    7569
Med_D    7479
Med_E    7471
Med_A    7440
Name: medicationprescribed, dtype: int64

In [28]:
hcdata.groupby('medicationprescribed').sum()

<ipython-input-28-f82c0d1a6d01>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  hcdata.groupby('medicationprescribed').sum()

,patientage,averageheartrate,averagebp,heightincm,weightinkg,paymentdue,lastvisitdaysago,visitdurationmins,numberoftests,prescriptioncost
medicationprescribed,,,,,,,,,,
Med_A,332692.0,591066.0,815561.0,1298771.0,516867.0,1.840296e+06,1358041.0,482485.0,29651.0,558695.508083
Med_B,340191.0,606564.0,836638.0,1332189.0,531384.0,1.887021e+06,1392538.0,499156.0,30511.0,573322.945604
Med_C,338388.0,602326.0,828510.0,1323744.0,527073.0,1.889377e+06,1380526.0,493302.0,30173.0,573206.672769
Med_D,332468.0,594525.0,819525.0,1304917.0,520427.0,1.872219e+06,1364479.0,482998.0,29946.0,558806.181160
Med_E,335065.0,594064.0,819281.0,1303951.0,520731.0,1.867912e+06,1363852.0,485818.0,29942.0,558460.765046

In [45]:
hcdata.groupby(['stateofresidence']).describe()

                 patientage                                                 \
                      count       mean        std   min    25%   50%   75%
stateofresidence
Alabama               752.0  44.188830  14.691102  18.0  33.00  44.0  54.0
Alaska                726.0  44.506887  14.856159  18.0  34.00  44.5  55.0
Arizona               749.0  45.214953  14.629488  18.0  35.00  45.0  56.0
Arkansas              785.0  44.206369  14.619693  18.0  34.00  43.0  55.0
California            771.0  44.797665  14.946243  18.0  34.00  45.0  55.0
Colorado              764.0  43.887435  14.161228  18.0  33.00  44.0  53.0
Connecticut           797.0  43.228356  14.976969  18.0  32.00  42.0  54.0
Delaware              751.0  44.921438  14.120735  18.0  35.00  45.0  55.0
Florida               749.0  45.154873  14.665888  18.0  35.00  46.0  56.0
Georgia               752.0  44.796543  14.366974  18.0  34.00  45.0  55.0
Hawaii                691.0  45.085384  13.608073  18.0  35.00  45.0  54.0
Idaho                 760.0  44.750000  13.989856  18.0  36.00  45.0  55.0
Illinois              730.0  45.239726  14.941727  18.0  34.00  45.0  55.0
Indiana               710.0  46.125352  14.492245  18.0  36.00  46.0  56.0
Iowa                  809.0  44.269468  14.674659  18.0  34.00  44.0  54.0
Kansas                793.0  44.061791  14.881433  18.0  34.00  43.0  55.0
Kentucky              804.0  44.684080  14.895642  18.0  34.00  44.0  55.0
Louisiana             737.0  43.636364  14.748920  18.0  33.00  44.0  53.0
Maine                 687.0  44.147016  14.372499  18.0  33.00  44.0  54.0
Maryland              742.0  45.412399  14.485779  18.0  36.00  45.0  56.0
Massachusetts         755.0  44.890066  14.510303  18.0  35.00  45.0  54.0
Michigan              725.0  44.609655  14.114006  18.0  35.00  44.0  54.0
Minnesota             812.0  44.800493  14.316989  18.0  34.00  45.0  55.0
Mississippi           783.0  44.919540  14.305756  18.0  35.00  46.0  55.0
Missouri              778.0  44.185090  14.243576  18.0  34.00  44.0  53.0
Montana               764.0  44.197644  14.689765  18.0  33.00  44.0  54.0
Nebraska              772.0  44.683938  14.390644  18.0  34.00  45.0  55.0
Nevada                736.0  45.554348  14.293799  18.0  36.00  45.5  55.0
New Hampshire         668.0  45.154192  13.992776  18.0  35.75  45.0  54.0
New Jersey            780.0  44.457692  14.829264  18.0  33.75  45.0  54.0
New Mexico            751.0  44.813582  14.977045  18.0  35.00  45.0  56.0
New York              785.0  44.298089  14.259272  18.0  35.00  44.0  53.0
North Carolina        731.0  45.307798  14.349633  18.0  35.00  45.0  54.0
North Dakota          755.0  44.000000  14.794974  18.0  34.50  43.0  55.0
Ohio                  770.0  43.948052  14.709405  18.0  34.00  43.0  53.0
Oklahoma              717.0  44.582985  14.716801  18.0  33.00  44.0  55.0
Oregon                764.0  43.930628  14.583754  18.0  33.00  44.0  55.0
Pennsylvania          741.0  45.215924  14.761228  18.0  35.00  44.0  55.0
Rhode Island          763.0  44.947575  14.836197  18.0  34.00  45.0  55.0
South Carolina        730.0  45.000000  14.789515  18.0  34.00  45.0  55.0
South Dakota          724.0  44.716851  14.519265  18.0  34.00  44.0  55.0
Tennessee             771.0  45.378729  14.693466  18.0  35.00  44.0  56.0
Texas                 756.0  45.263228  14.656085  18.0  35.00  45.0  56.0
Utah                  715.0  43.816783  14.328919  18.0  34.00  43.0  54.0
Vermont               746.0  44.920912  14.701337  18.0  34.00  45.0  54.0
Virginia              727.0  44.176066  14.869009  18.0  33.00  43.0  54.0
Washington            728.0  44.453297  14.120157  18.0  34.00  44.0  54.0
West Virginia         738.0  44.486450  14.168705  18.0  34.25  45.0  54.0
Wisconsin             786.0  45.192112  15.064447  18.0  34.00  45.0  56.0
Wyoming               764.0  44.887435  14.633322  18.0  35.00  44.0  55.0

                        averageheartrate             ... averagecardio         \
                    max            count       mean  ...           75%    max
stateofresidence                                     ...
Alabama            86.0            752.0  79.801862  ...       100.500  124.0
Alaska             85.0            726.0  79.585399  ...       100.500  118.0
Arizona            94.0            749.0  79.396529  ...       100.500  118.5
Arkansas           97.0            785.0  78.782166  ...        99.500  120.5
California         90.0            771.0  78.996109  ...        99.500  118.0
Colorado           90.0            764.0  79.528796  ...       100.500  121.0
Connecticut        90.0            797.0  79.496863  ...       100.500  127.0
Delaware           87.0            751.0  80.010652  ...       100.500  126.0
Florida            88.0            749.0  80.069426  ...       101.000  117.0
Georgia            95.0            752.0  79.481383  ...       100.500  121.5
Hawaii             85.0            691.0  79.913169  ...       100.500  122.0
Idaho              82.0            760.0  79.061842  ...       100.000  121.0
Illinois           93.0            730.0  78.793151  ...       100.000  118.0
Indiana           100.0            710.0  79.759155  ...       101.000  117.5
Iowa               99.0            809.0  79.836836  ...       101.500  122.0
Kansas             90.0            793.0  79.542245  ...       100.500  116.5
Kentucky           98.0            804.0  79.619403  ...       100.000  121.5
Louisiana         100.0            737.0  79.843962  ...       100.000  118.5
Maine              86.0            687.0  79.574964  ...       101.000  124.0
Maryland           86.0            742.0  79.471698  ...       100.000  116.5
Massachusetts      99.0            755.0  79.180132  ...       100.500  123.0
Michigan           88.0            725.0  79.419310  ...       101.000  119.5
Minnesota          89.0            812.0  79.153941  ...       100.500  120.0
Mississippi        94.0            783.0  79.363985  ...       100.250  117.0
Missouri           94.0            778.0  79.316195  ...       100.875  122.0
Montana            96.0            764.0  79.250000  ...       100.500  117.0
Nebraska           93.0            772.0  80.229275  ...       101.500  121.5
Nevada            100.0            736.0  79.718750  ...       101.000  118.0
New Hampshire      97.0            668.0  79.732036  ...       101.000  120.5
New Jersey         96.0            780.0  79.915385  ...       101.000  119.5
New Mexico         89.0            751.0  79.946738  ...       100.750  119.0
New York           89.0            785.0  79.105732  ...       101.000  117.0
North Carolina     97.0            731.0  79.164159  ...       100.500  119.0
North Dakota       90.0            755.0  78.849007  ...       100.500  120.0
Ohio               90.0            770.0  79.240260  ...       100.500  120.0
Oklahoma           92.0            717.0  79.900976  ...       101.000  121.5
Oregon             95.0            764.0  79.867801  ...       100.500  122.5
Pennsylvania       95.0            741.0  79.775978  ...       101.000  118.0
Rhode Island       93.0            763.0  79.646134  ...       100.500  118.0
South Carolina     95.0            730.0  78.764384  ...       100.500  119.5
South Dakota       96.0            724.0  79.406077  ...       100.500  118.5
Tennessee          89.0            771.0  80.050584  ...       101.500  122.5
Texas              95.0            756.0  79.654762  ...       100.500  120.5
Utah               98.0            715.0  79.187413  ...       100.500  120.0
Vermont           100.0            746.0  78.911528  ...       100.500  122.5
Virginia          100.0            727.0  79.654746  ...       100.500  121.5
Washington         91.0            728.0  79.416209  ...       101.000  121.5
West Virginia      92.0            738.0  79.550136  ...       100.500  119.5
Wisconsin          98.0            786.0  79.232824  ...       100.000  124.0
Wyoming            95.0            764.0  79.674084  ...       101.000  116.5

                 averagecardioval                                          \
                            count       mean        std   min   25%   50%
stateofresidence
Alabama                     752.0  79.801862   9.667541  50.0  73.0  79.0
Alaska                      726.0  79.585399   9.919692  52.0  73.0  80.0
Arizona                     749.0  79.396529   9.838348  52.0  72.0  80.0
Arkansas                    785.0  78.782166   9.825373  54.0  72.0  78.0
California                  771.0  78.996109   9.764831  50.0  73.0  79.0
Colorado                    764.0  79.528796   9.787946  50.0  72.0  79.5
Connecticut                 797.0  79.496863  10.088505  50.0  73.0  80.0
Delaware                    751.0  80.010652  10.568249  50.0  73.0  80.0
Florida                     749.0  80.069426   9.719487  50.0  73.0  80.0
Georgia                     752.0  79.481383   9.965836  50.0  73.0  79.0
Hawaii                      691.0  79.913169  10.021194  51.0  73.0  80.0
Idaho                       760.0  79.061842   9.956698  50.0  73.0  79.0
Illinois                    730.0  78.793151  10.081408  50.0  72.0  79.0
Indiana                     710.0  79.759155   9.968202  52.0  72.0  79.0
Iowa                        809.0  79.836836  10.000276  50.0  73.0  80.0
Kansas                      793.0  79.542245  10.001189  50.0  73.0  79.0
Kentucky                    804.0  79.619403  10.225450  50.0  73.0  79.0
Louisiana                   737.0  79.843962   9.880747  51.0  72.0  79.0
Maine                       687.0  79.574964   9.911848  50.0  73.0  79.0
Maryland                    742.0  79.471698  10.025535  50.0  73.0  79.0
Massachusetts               755.0  79.180132   9.815236  50.0  72.0  79.0
Michigan                    725.0  79.419310  10.087910  50.0  73.0  80.0
Minnesota                   812.0  79.153941  10.354253  50.0  72.0  79.0
Mississippi                 783.0  79.363985   9.900093  50.0  73.0  80.0
Missouri                    778.0  79.316195   9.677969  50.0  73.0  80.0
Montana                     764.0  79.250000  10.125507  50.0  72.0  79.0
Nebraska                    772.0  80.229275  10.314284  50.0  73.0  80.0
Nevada                      736.0  79.718750   9.767138  53.0  73.0  80.0
New Hampshire               668.0  79.732036   9.747105  51.0  73.0  80.0
New Jersey                  780.0  79.915385   9.928914  53.0  73.0  80.0
New Mexico                  751.0  79.946738  10.124417  50.0  73.0  80.0
New York                    785.0  79.105732  10.364789  50.0  72.0  79.0
North Carolina              731.0  79.164159   9.932395  50.0  73.0  79.0
North Dakota                755.0  78.849007  10.125131  50.0  72.0  79.0
Ohio                        770.0  79.240260  10.284418  50.0  73.0  79.0
Oklahoma                    717.0  79.900976  10.225391  50.0  73.0  80.0
Oregon                      764.0  79.867801  10.094030  53.0  73.0  80.0
Pennsylvania                741.0  79.775978   9.890264  50.0  73.0  80.0
Rhode Island                763.0  79.646134   9.651027  51.0  74.0  80.0
South Carolina              730.0  78.764384  10.068318  50.0  72.0  78.5
South Dakota                724.0  79.406077   9.718629  50.0  73.0  80.0
Tennessee                   771.0  80.050584  10.639367  50.0  73.0  81.0
Texas                       756.0  79.654762   9.988264  50.0  73.0  80.0
Utah                        715.0  79.187413  10.387107  50.0  73.0  79.0
Vermont                     746.0  78.911528  10.074232  50.0  72.0  79.0
Virginia                    727.0  79.654746   9.966082  50.0  73.5  80.0
Washington                  728.0  79.416209  10.097931  52.0  72.0  80.0
West Virginia               738.0  79.550136   9.513730  50.0  73.0  80.0
Wisconsin                   786.0  79.232824  10.174678  50.0  72.0  79.0
Wyoming                     764.0  79.674084   9.879739  50.0  73.0  80.0


                    75%    max
stateofresidence
Alabama           87.00  110.0
Alaska            86.00  107.0
Arizona           86.00  113.0
Arkansas          86.00  116.0
California        86.00  106.0
Colorado          86.00  108.0
Connecticut       86.00  116.0
Delaware          87.00  112.0
Florida           87.00  109.0
Georgia           86.00  110.0
Hawaii            86.00  115.0
Idaho             85.00  109.0
Illinois          86.00  113.0
Indiana           87.00  110.0
Iowa              87.00  110.0
Kansas            87.00  114.0
Kentucky          86.00  120.0
Louisiana         86.00  110.0
Maine             86.00  109.0
Maryland          87.00  109.0
Massachusetts     86.00  109.0
Michigan          85.00  117.0
Minnesota         86.00  114.0
Mississippi       86.00  108.0
Missouri          86.00  113.0
Montana           86.00  109.0
Nebraska          87.00  109.0
Nevada            86.00  110.0
New Hampshire     86.00  104.0
New Jersey        86.00  110.0
New Mexico        87.00  110.0
New York          86.00  114.0
North Carolina    86.00  107.0
North Dakota      85.00  107.0
Ohio              85.75  113.0
Oklahoma          86.00  110.0
Oregon            87.00  115.0
Pennsylvania      87.00  115.0
Rhode Island      86.00  109.0
South Carolina    85.00  111.0
South Dakota      86.00  114.0
Tennessee         87.00  115.0
Texas             86.00  110.0
Utah              86.00  111.0
Vermont           85.00  112.0
Virginia          86.00  106.0
Washington        86.00  111.0
West Virginia     86.00  106.0
Wisconsin         86.00  119.0
Wyoming           86.00  113.0

[50 rows x 96 columns]

In [49]:
grouping_data = data.groupby ('stateofresidence').agg({'mean'})
grouping_data

<ipython-input-49-9699924e186b>:1: FutureWarning: ['gender', 'cityofresidence', 'hasinsurance', 'visitedlastmonth', 'paymentmethod', 'preferreddoctor', 'diseasediagnosed', 'medicationprescribed', 'typeofappointment'] did not aggregate successfully. If any error is raised this will raise in a future version of pandas. Drop these columns/ops to avoid this warning.
  grouping_data = data.groupby ('stateofresidence').agg({'mean'})

,patientage,averageheartrate,averagebp,heightincm,weightinkg,paymentdue,lastvisitdaysago,visitdurationmins,numberoftests,prescriptioncost
,mean,mean,mean,mean,mean,mean,mean,mean,mean,mean
stateofresidence,,,,,,,,,,
Alabama,44.188830,79.801862,110.196809,174.565160,68.591755,241.631368,182.566489,63.343085,4.051862,73.470477
Alaska,44.506887,79.585399,109.360882,174.530303,69.592287,251.524239,182.077135,64.318182,3.904959,74.915800
Arizona,45.214953,79.396529,109.568758,174.116155,69.267023,249.583396,182.483311,65.643525,3.959947,72.761381
Arkansas,44.206369,78.782166,109.594904,174.496815,70.501911,246.874393,182.682803,62.719745,3.970701,76.849926
California,44.797665,78.996109,108.744488,174.062257,70.551232,240.905936,182.236057,65.223087,3.992218,71.590880
Colorado,43.887435,79.528796,110.062827,174.747382,69.683246,245.128486,182.693717,65.001309,4.024869,75.255174
Connecticut,43.228356,79.496863,109.894605,174.727729,68.774153,253.392735,182.115433,63.563363,4.060226,74.901103
Delaware,44.921438,80.010652,108.770972,173.989348,69.966711,257.691674,181.936085,65.039947,4.031957,75.203833
Florida,45.154873,80.069426,108.983979,175.056075,68.861148,242.933002,182.353805,64.579439,3.958611,73.611270
Georgia,44.796543,79.481383,109.666223,175.449468,69.117021,247.350820,182.591755,64.861702,4.053191,74.745936
Hawaii,45.085384,79.913169,109.749638,174.918958,69.439942,251.090367,181.639653,63.991317,4.059334,75.498822
Idaho,44.750000,79.061842,109.775000,174.144737,69.772368,258.642323,182.640789,67.973684,3.932895,74.008739
Illinois,45.239726,78.793151,110.120548,175.090411,69.773973,245.388474,182.421918,65.312329,4.049315,75.048085
Indiana,46.125352,79.759155,110.098592,175.277465,68.878873,244.925417,182.798592,64.808451,3.956338,74.790130
Iowa,44.269468,79.836836,110.084054,174.886279,69.095179,250.727277,182.758962,66.050680,3.936959,75.962679
Kansas,44.061791,79.542245,108.187894,173.703657,70.607818,258.078051,182.564943,61.988651,4.060530,74.066540
Kentucky,44.684080,79.619403,109.972637,175.518657,69.589552,248.821562,181.965174,65.174129,3.946517,75.540341
Louisiana,43.636364,79.843962,108.846676,174.454545,69.379919,250.825109,182.025780,63.428765,4.002714,74.424266
Maine,44.147016,79.574964,110.353712,174.826783,68.899563,246.528651,182.666667,65.184862,3.975255,74.421940
Maryland,45.412399,79.471698,108.277628,174.770889,69.338275,249.400819,182.204852,67.342318,3.989218,69.617250
Massachusetts,44.890066,79.180132,109.180132,175.803974,69.278146,249.443352,182.601325,64.913907,3.941722,73.861133
Michigan,44.609655,79.419310,109.950345,174.471724,69.517241,251.272128,182.748966,65.206897,3.990345,78.183806
Minnesota,44.800493,79.153941,109.203202,174.044335,70.194581,240.312239,182.801724,63.572660,4.040640,75.165350
Mississippi,44.919540,79.363985,108.256705,174.169860,69.601533,253.212180,182.453384,65.939974,4.047254,77.486275
Missouri,44.185090,79.316195,110.510283,174.473008,69.811054,243.695300,182.263496,64.665810,3.996144,78.067041
Montana,44.197644,79.250000,109.776178,174.308901,70.108639,239.279815,182.571990,63.494764,4.005236,76.999507
Nebraska,44.683938,80.229275,109.838083,174.549223,69.632124,244.952221,182.532383,64.290155,4.093264,71.940537
Nevada,45.554348,79.718750,110.013587,174.372283,69.949728,244.923081,182.438859,66.188859,3.865489,77.169527
New Hampshire,45.154192,79.732036,109.931138,174.227545,69.691617,249.469835,183.031437,65.013473,4.034431,75.957196
New Jersey,44.457692,79.915385,109.888462,174.448718,70.201282,248.345113,182.603846,66.600000,3.925641,75.661448
New Mexico,44.813582,79.946738,109.604527,174.980027,70.512650,258.471048,182.412783,67.348868,3.872170,76.407224
New York,44.298089,79.105732,109.872611,174.656051,69.467516,242.686488,182.010191,66.289172,4.025478,74.866191
North Carolina,45.307798,79.164159,110.476060,174.965800,70.238030,250.176185,182.091655,63.140903,4.047880,73.554198
North Dakota,44.000000,78.849007,109.463576,174.815894,69.376159,243.643703,182.495364,64.450331,3.969536,76.700040
Ohio,43.948052,79.240260,109.393506,175.038961,70.414286,248.073586,182.589610,65.367532,4.087013,75.749178
Oklahoma,44.582985,79.900976,109.446304,175.114365,68.644351,253.097981,183.016736,63.576011,3.963738,74.321453
Oregon,43.930628,79.867801,108.976440,174.414921,69.121728,245.693998,182.750000,63.967277,4.019634,72.573666
Pennsylvania,45.215924,79.775978,109.835358,173.974359,69.622132,245.131635,182.441296,64.488529,4.144399,74.335241
Rhode Island,44.947575,79.646134,109.880734,174.550459,69.837484,254.531556,182.885976,64.752294,3.958060,73.480733
South Carolina,45.000000,78.764384,110.026027,174.263014,69.889041,254.259941,182.202740,65.809589,3.958904,77.490037
South Dakota,44.716851,79.406077,110.314917,174.077348,70.096685,247.422476,182.758287,65.038674,3.908840,78.465438
Tennessee,45.378729,80.050584,110.108949,173.658885,69.931258,248.676696,182.106355,65.975357,3.984436,75.160979
Texas,45.263228,79.654762,109.773810,174.966931,69.773810,240.066784,182.421958,66.732804,4.038360,71.770773
Utah,43.816783,79.187413,109.067133,174.795804,69.586014,257.725055,182.079720,66.660140,4.005594,75.419210
Vermont,44.920912,78.911528,109.107239,174.489276,69.321716,249.408877,182.403485,65.565684,3.945040,75.578360
Virginia,44.176066,79.654746,109.250344,174.314993,68.900963,246.903017,182.309491,65.689133,3.936726,74.981708
Washington,44.453297,79.416209,109.719780,174.328297,69.335165,260.099044,182.994505,64.674451,3.989011,77.222543
West Virginia,44.486450,79.550136,109.227642,175.189702,69.823848,253.074391,182.161247,64.859079,4.016260,78.333102
Wisconsin,45.192112,79.232824,108.914758,174.222646,69.783715,249.018364,182.942748,66.017812,4.045802,77.692891
Wyoming,44.887435,79.674084,109.842932,174.645288,68.316754,251.593734,182.502618,64.479058,4.009162,72.794272

### Pivot Tables for Multi-dimentional analysis

In [53]:
hcdata.pivot_table(index='stateofresidence', columns='heightincm', values='weightinkg', aggfunc='mean')

heightincm,140.0,141.0,142.0,143.0,144.0,145.0,146.0,147.0,148.0,149.0,...,201.0,202.0,203.0,204.0,205.0,206.0,207.0,208.0,209.0,210.0
stateofresidence,,,,,,,,,,,,,,,,,,,,,
Alabama,NaN,NaN,NaN,NaN,NaN,NaN,56.0,NaN,66.500000,84.0,...,81.333333,62.000000,72.0,NaN,NaN,52.000000,NaN,NaN,NaN,NaN
Alaska,104.000000,NaN,NaN,NaN,NaN,50.0,75.0,NaN,98.000000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,54.0,NaN,NaN,49.0
Arizona,NaN,NaN,NaN,NaN,63.000000,59.0,NaN,NaN,90.000000,74.5,...,55.000000,NaN,78.0,NaN,NaN,60.000000,60.0,NaN,NaN,68.0
Arkansas,NaN,NaN,67.0,NaN,81.000000,NaN,NaN,73.000000,NaN,65.5,...,59.000000,76.000000,53.0,NaN,65.000000,59.000000,NaN,NaN,NaN,78.0
California,NaN,NaN,NaN,56.0,NaN,NaN,105.0,NaN,55.000000,81.0,...,60.000000,66.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Colorado,NaN,NaN,NaN,NaN,NaN,85.0,NaN,NaN,66.666667,62.0,...,63.000000,NaN,44.0,63.000000,NaN,NaN,NaN,NaN,NaN,NaN
Connecticut,NaN,NaN,79.0,NaN,59.000000,NaN,NaN,50.000000,81.000000,87.0,...,65.000000,NaN,74.0,NaN,81.000000,NaN,59.0,NaN,NaN,NaN
Delaware,NaN,NaN,NaN,NaN,54.000000,NaN,83.0,NaN,78.000000,72.0,...,83.000000,NaN,NaN,71.500000,NaN,NaN,45.0,NaN,79.0,NaN
Florida,NaN,NaN,NaN,NaN,78.000000,NaN,NaN,NaN,93.000000,60.5,...,57.000000,NaN,64.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Georgia,118.000000,NaN,NaN,NaN,NaN,NaN,96.0,NaN,54.000000,53.0,...,70.666667,NaN,NaN,82.000000,NaN,NaN,NaN,NaN,NaN,NaN
Hawaii,NaN,NaN,NaN,50.0,NaN,52.0,84.0,NaN,NaN,75.0,...,NaN,66.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Idaho,NaN,NaN,NaN,NaN,NaN,NaN,81.0,78.500000,67.000000,52.0,...,NaN,NaN,89.0,NaN,NaN,NaN,NaN,NaN,NaN,71.0
Illinois,NaN,NaN,NaN,NaN,77.000000,NaN,NaN,NaN,NaN,NaN,...,NaN,78.500000,66.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Indiana,NaN,75.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,73.0,...,NaN,54.000000,NaN,68.333333,NaN,NaN,NaN,66.0,NaN,NaN
Iowa,NaN,NaN,NaN,NaN,NaN,69.0,NaN,69.000000,NaN,NaN,...,NaN,64.000000,46.0,51.000000,NaN,NaN,NaN,NaN,NaN,NaN
Kansas,NaN,NaN,NaN,53.0,NaN,NaN,68.0,58.000000,69.500000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,90.0,NaN,NaN,NaN
Kentucky,NaN,NaN,NaN,NaN,63.000000,72.0,NaN,67.500000,62.000000,NaN,...,57.000000,62.500000,72.0,44.000000,87.000000,76.000000,NaN,NaN,71.0,NaN
Louisiana,77.000000,NaN,NaN,73.0,NaN,NaN,NaN,NaN,NaN,NaN,...,77.333333,72.666667,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Maine,NaN,NaN,NaN,NaN,NaN,NaN,46.0,51.000000,NaN,83.0,...,93.000000,NaN,NaN,NaN,79.000000,NaN,NaN,NaN,NaN,NaN
Maryland,NaN,NaN,81.0,NaN,NaN,NaN,NaN,84.000000,91.000000,57.0,...,78.000000,40.000000,NaN,NaN,75.000000,NaN,NaN,NaN,NaN,73.0
Massachusetts,NaN,NaN,NaN,61.0,NaN,NaN,NaN,NaN,66.000000,65.0,...,85.000000,NaN,NaN,NaN,43.500000,69.000000,60.0,NaN,40.0,NaN
Michigan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,78.000000,NaN,NaN,77.000000,NaN,NaN,NaN,NaN,NaN,40.0
Minnesota,61.000000,NaN,NaN,NaN,80.000000,43.0,NaN,NaN,NaN,60.0,...,NaN,74.500000,NaN,NaN,NaN,106.000000,NaN,NaN,70.0,NaN
Mississippi,NaN,NaN,NaN,NaN,NaN,NaN,NaN,83.000000,62.000000,47.0,...,68.000000,74.000000,NaN,NaN,57.000000,NaN,NaN,NaN,NaN,NaN
Missouri,NaN,NaN,NaN,NaN,66.000000,NaN,NaN,80.000000,NaN,50.0,...,58.000000,NaN,74.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Montana,74.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,62.333333,NaN,...,71.500000,63.000000,64.0,74.000000,77.333333,NaN,NaN,NaN,NaN,105.0
Nebraska,NaN,NaN,NaN,NaN,NaN,NaN,77.0,58.666667,NaN,77.0,...,NaN,65.000000,75.0,69.000000,NaN,NaN,56.0,NaN,NaN,NaN
Nevada,73.000000,NaN,NaN,67.0,52.000000,NaN,NaN,89.000000,75.500000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,75.0
New Hampshire,NaN,NaN,NaN,NaN,NaN,NaN,NaN,77.000000,40.000000,48.0,...,NaN,NaN,NaN,NaN,72.000000,NaN,NaN,NaN,NaN,NaN
New Jersey,86.000000,NaN,NaN,NaN,61.500000,NaN,73.0,66.000000,70.500000,89.0,...,89.333333,NaN,107.0,NaN,79.000000,94.000000,NaN,NaN,NaN,NaN
New Mexico,NaN,NaN,NaN,NaN,NaN,46.0,83.0,NaN,73.666667,60.0,...,58.000000,81.000000,74.0,61.000000,NaN,58.000000,NaN,NaN,NaN,NaN
New York,NaN,NaN,NaN,NaN,77.000000,NaN,NaN,NaN,NaN,NaN,...,58.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
North Carolina,54.666667,56.0,NaN,NaN,81.000000,NaN,50.0,NaN,NaN,63.0,...,NaN,NaN,76.0,57.500000,NaN,56.000000,NaN,NaN,NaN,NaN
North Dakota,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,68.500000,NaN,...,NaN,48.000000,71.0,66.000000,91.000000,NaN,NaN,NaN,NaN,NaN
Ohio,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,61.0,...,75.500000,NaN,NaN,NaN,NaN,99.000000,NaN,65.0,NaN,64.0
Oklahoma,64.000000,NaN,NaN,NaN,59.000000,NaN,58.0,NaN,60.000000,NaN,...,72.000000,NaN,NaN,NaN,NaN,NaN,44.0,67.0,NaN,NaN
Oregon,NaN,NaN,NaN,NaN,40.000000,NaN,NaN,NaN,75.750000,71.0,...,77.000000,76.000000,NaN,62.000000,NaN,NaN,NaN,NaN,NaN,NaN
Pennsylvania,NaN,NaN,NaN,NaN,NaN,NaN,NaN,66.333333,NaN,82.0,...,51.000000,NaN,64.0,83.000000,NaN,NaN,NaN,NaN,NaN,NaN
Rhode Island,NaN,NaN,77.0,NaN,NaN,86.0,67.0,NaN,82.500000,59.0,...,NaN,54.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
South Carolina,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,80.333333,68.0,...,NaN,NaN,72.0,NaN,NaN,NaN,NaN,NaN,59.0,NaN
South Dakota,NaN,55.0,NaN,66.0,60.333333,62.0,NaN,81.000000,66.000000,NaN,...,66.666667,59.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Tennessee,NaN,NaN,NaN,NaN,NaN,61.0,NaN,74.500000,90.000000,73.0,...,71.000000,61.000000,71.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Texas,86.000000,NaN,NaN,NaN,NaN,NaN,NaN,57.000000,NaN,NaN,...,NaN,61.000000,NaN,100.500000,NaN,NaN,NaN,93.0,NaN,NaN
Utah,NaN,NaN,NaN,NaN,75.000000,97.0,NaN,75.000000,56.000000,70.0,...,54.000000,40.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Vermont,NaN,NaN,NaN,NaN,59.000000,NaN,NaN,NaN,55.000000,NaN,...,NaN,74.000000,NaN,NaN,NaN,NaN,NaN,48.0,NaN,58.0
Virginia,NaN,NaN,NaN,NaN,68.000000,NaN,67.0,64.000000,79.000000,89.0,...,60.000000,NaN,NaN,NaN,61.000000,NaN,NaN,NaN,NaN,NaN
Washington,NaN,NaN,NaN,NaN,81.000000,NaN,NaN,71.000000,57.000000,NaN,...,NaN,73.000000,82.0,NaN,61.000000,NaN,NaN,NaN,NaN,NaN
West Virginia,NaN,NaN,NaN,60.0,NaN,108.0,NaN,NaN,47.000000,52.0,...,84.000000,NaN,81.0,NaN,NaN,50.666667,NaN,NaN,NaN,NaN
Wisconsin,NaN,NaN,NaN,NaN,NaN,74.0,40.0,62.000000,NaN,47.0,...,NaN,NaN,NaN,69.000000,NaN,NaN,NaN,NaN,NaN,NaN
Wyoming,NaN,NaN,NaN,NaN,NaN,NaN,73.0,NaN,63.000000,75.0,...,52.000000,76.500000,NaN,NaN,76.000000,72.000000,NaN,NaN,NaN,NaN

In [54]:
hcdata.pivot_table(index='gender', columns='heightincm', values='weightinkg', aggfunc='mean')

heightincm,140.0,141.0,142.0,143.0,144.0,145.0,146.0,147.0,148.0,149.0,...,201.0,202.0,203.0,204.0,205.0,206.0,207.0,208.0,209.0,210.0
gender,,,,,,,,,,,,,,,,,,,,,
Female,79.5,NaN,NaN,NaN,66.20,74.000000,70.000000,73.833333,72.136364,69.357143,...,70.000000,65.000000,71.000000,64.818182,78.125000,86.000000,51.500000,59.666667,60.0,105.0
Male,81.6,NaN,75.0,53.000000,65.25,68.333333,62.333333,71.416667,69.187500,66.050000,...,70.523810,72.000000,76.375000,78.500000,60.666667,54.555556,63.666667,67.000000,NaN,69.0
Other,68.0,62.0,79.0,65.714286,67.90,68.571429,79.111111,66.600000,73.647059,65.600000,...,68.714286,63.214286,69.545455,68.666667,69.571429,56.000000,58.000000,93.000000,79.0,61.5

In [57]:
hcdata.pivot_table(index='preferreddoctor', columns='heightincm', values='weightinkg', aggfunc='mean')

heightincm,140.0,141.0,142.0,143.0,144.0,145.0,146.0,147.0,148.0,149.0,...,201.0,202.0,203.0,204.0,205.0,206.0,207.0,208.0,209.0,210.0
preferreddoctor,,,,,,,,,,,,,,,,,,,,,
Dr. Brown,91.000000,NaN,81.0,66.500000,71.833333,51.00,90.000000,71.600000,73.583333,60.800000,...,66.909091,69.888889,76.250000,70.285714,64.000000,65.000000,60.000000,NaN,79.0,78.0
Dr. Johnson,60.500000,NaN,NaN,56.000000,63.500000,60.00,54.000000,72.400000,74.857143,61.363636,...,70.117647,69.555556,75.666667,81.250000,72.571429,67.666667,66.666667,NaN,NaN,58.0
Dr. Jones,75.000000,75.0,NaN,56.666667,69.333333,69.50,74.200000,70.888889,68.846154,66.300000,...,67.100000,60.833333,69.000000,53.333333,71.666667,60.000000,49.333333,57.0,49.5,73.0
Dr. Smith,71.000000,55.0,78.0,73.000000,64.000000,78.50,67.833333,66.333333,68.200000,74.833333,...,74.923077,65.111111,73.857143,68.166667,80.000000,NaN,NaN,67.0,70.5,58.5
Dr. Williams,77.666667,56.0,67.0,57.000000,67.800000,76.75,79.333333,64.000000,74.000000,72.000000,...,65.000000,60.500000,66.250000,80.500000,74.000000,67.857143,NaN,79.0,NaN,70.5

## Introduction to Alternative Libraries- Polars and Time

In [74]:
import polars as pl
import time

In [107]:
hcdata

,patientage,gender,cityofresidence,stateofresidence,hasinsurance,visitedlastmonth,paymentmethod,preferreddoctor,diseasediagnosed,medicationprescribed,...,heightincm,weightinkg,paymentdue,lastvisitdaysago,visitdurationmins,numberoftests,prescriptioncost,patientunder40,averagecardio,averagecardioval
0,45.0,Other,West Brian,Kentucky,Yes,Yes,Insurance,Dr. Williams,Flu,Med_E,...,183.0,70.0,65.457216,193.0,92.0,5.0,15.717517,Older,88.5,66.0
4,48.0,Female,Birdmouth,Montana,No,No,Insurance,Dr. Brown,None,Med_C,...,186.0,87.0,264.214737,188.0,113.0,3.0,77.483113,Older,91.0,93.0
7,52.0,Male,Vanessaburgh,Connecticut,Yes,Yes,Insurance,Dr. Williams,Flu,Med_E,...,170.0,47.0,387.085044,179.0,108.0,2.0,76.965926,Older,114.0,99.0
8,20.0,Female,West Briannabury,Montana,No,Yes,Card,Dr. Jones,Flu,Med_C,...,173.0,86.0,172.548343,174.0,91.0,2.0,142.317108,Younger,87.5,67.0
11,40.0,Female,Jonesmouth,Rhode Island,No,No,Card,Dr. Jones,Covid-19,Med_E,...,166.0,82.0,299.142676,193.0,92.0,1.0,77.715360,Older,85.5,65.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
104992,44.0,Female,Port Tracistad,Alaska,Yes,No,Insurance,Dr. Brown,Cold,Med_A,...,178.0,66.0,462.565671,189.0,55.0,3.0,59.746318,Older,84.5,76.0
104993,42.0,Female,West Annaport,Florida,Yes,No,Cash,Dr. Johnson,Covid-19,Med_D,...,171.0,78.0,131.356326,185.0,22.0,6.0,104.430167,Older,104.5,80.0
104994,53.0,Female,Michelleburgh,South Dakota,No,No,Card,Dr. Williams,Flu,Med_B,...,172.0,75.0,488.031604,167.0,25.0,5.0,69.542286,Older,88.5,68.0
104995,74.0,Other,West Anthony,Oklahoma,Yes,No,Card,Dr. Williams,Covid-19,Med_E,...,169.0,61.0,309.164446,183.0,10.0,3.0,63.204788,Older,88.5,65.0
104997,51.0,Female,Lake Lisachester,Nebraska,Yes,Yes,Insurance,Dr. Williams,Allergy,Med_D,...,179.0,71.0,320.830418,172.0,39.0,3.0,35.622420,Older,103.5,89.0

### Loading data with Polars

In [92]:
pl_hcdata = pl.read_csv('https://raw.githubusercontent.com/amnasyed1/datasci_2_manipulation/main/dataset/healthcare_data_cleaning.csv')
print(pl_hcdata)

shape: (105_000, 20)
┌───────────┬────────┬────────────┬────────────┬───┬────────────┬────────────┬────────────┬────────────┐
│ Patient   ┆ Gender ┆ City of    ┆ State of   ┆ … ┆ Last Visit ┆ Visit      ┆ Number of  ┆ Prescripti │
│ Age       ┆ ---    ┆ Residence  ┆ Residence  ┆   ┆ (days ago) ┆ Duration   ┆ Tests      ┆ on Cost    │
│ ---       ┆ str    ┆ ---        ┆ ---        ┆   ┆ ---        ┆ (mins)     ┆ ---        ┆ ($)        │
│ str       ┆        ┆ str        ┆ str        ┆   ┆ str        ┆ ---        ┆ str        ┆ ---        │
│           ┆        ┆            ┆            ┆   ┆            ┆ str        ┆            ┆ str        │
╞═══════════╪════════╪════════════╪════════════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ 45        ┆ Other  ┆ West Brian ┆ Kentucky   ┆ … ┆ 193        ┆ 92         ┆ 5          ┆ 15.7175173 │
│           ┆        ┆            ┆            ┆   ┆            ┆            ┆            ┆ 5532889    │
│ 25        ┆ Female ┆ East Jocel ┆ Colorado   ┆ … ┆ 195        ┆ missing    ┆ 4          ┆ 80.7864728 │
│           ┆        ┆ ynfurt     ┆            ┆   ┆            ┆            ┆            ┆ 4463952    │
│ 51        ┆ Other  ┆ South Lind ┆ Ohio       ┆ … ┆ missing    ┆ 37         ┆ 2          ┆ 64.3921393 │
│           ┆        ┆ seyland    ┆            ┆   ┆            ┆            ┆            ┆ 009105     │
│ 18        ┆ Female ┆ Taylorfort ┆ Pennsylvan ┆ … ┆ 175        ┆ 108        ┆ 2          ┆ 8.87285921 │
│           ┆        ┆            ┆ ia         ┆   ┆            ┆            ┆            ┆ 5315316    │
│ …         ┆ …      ┆ …          ┆ …          ┆ … ┆ …          ┆ …          ┆ …          ┆ …          │
│ 37        ┆ Male   ┆ Mckeetown  ┆ Utah       ┆ … ┆ 191        ┆ 47         ┆ 2          ┆ 113.867640 │
│           ┆        ┆            ┆            ┆   ┆            ┆            ┆            ┆ 25370326   │
│ 51        ┆ Female ┆ Lake Lisac ┆ Nebraska   ┆ … ┆ 172        ┆ 39         ┆ 3          ┆ 35.6224202 │
│           ┆        ┆ hester     ┆            ┆   ┆            ┆            ┆            ┆ 32475356   │
│ missing   ┆ Female ┆ Heidiborou ┆ missing    ┆ … ┆ 180        ┆ 79         ┆ missing    ┆ 124.408340 │
│           ┆        ┆ gh         ┆            ┆   ┆            ┆            ┆            ┆ 9893742    │
│ 45        ┆ Female ┆ South      ┆ Massachuse ┆ … ┆ 167        ┆ 81         ┆ missing    ┆ 87.9106014 │
│           ┆        ┆ Jeffrey    ┆ tts        ┆   ┆            ┆            ┆            ┆ 9353706    │
└───────────┴────────┴────────────┴────────────┴───┴────────────┴────────────┴────────────┴────────────┘

In [93]:
print ("number of rows:", hcdata.shape[0])
print ("number of columns:", hcdata.shape[1])

number of rows: 37594
number of columns: 23

In [94]:
print(hcdata.head(5))

    patientage  gender   cityofresidence stateofresidence hasinsurance  \
0         45.0   Other        West Brian         Kentucky          Yes
4         48.0  Female         Birdmouth          Montana           No
7         52.0    Male      Vanessaburgh      Connecticut          Yes
8         20.0  Female  West Briannabury          Montana           No
11        40.0  Female        Jonesmouth     Rhode Island           No

   visitedlastmonth paymentmethod preferreddoctor diseasediagnosed  \
0               Yes     Insurance    Dr. Williams              Flu
4                No     Insurance       Dr. Brown             None
7               Yes     Insurance    Dr. Williams              Flu
8               Yes          Card       Dr. Jones              Flu
11               No          Card       Dr. Jones         Covid-19

   medicationprescribed  ... heightincm  weightinkg  paymentdue  \
0                 Med_E  ...      183.0        70.0   65.457216
4                 Med_C  ...      186.0        87.0  264.214737
7                 Med_E  ...      170.0        47.0  387.085044
8                 Med_C  ...      173.0        86.0  172.548343
11                Med_E  ...      166.0        82.0  299.142676

    lastvisitdaysago  visitdurationmins  numberoftests  prescriptioncost  \
0              193.0               92.0            5.0         15.717517
4              188.0              113.0            3.0         77.483113
7              179.0              108.0            2.0         76.965926
8              174.0               91.0            2.0        142.317108
11             193.0               92.0            1.0         77.715360

    patientunder40  averagecardio  averagecardioval
0            Older           88.5              66.0
4            Older           91.0              93.0
7            Older          114.0              99.0
8          Younger           87.5              67.0
11           Older           85.5              65.0

[5 rows x 23 columns]

In [95]:
print(hcdata.tail())

        patientage  gender   cityofresidence stateofresidence hasinsurance  \
104992        44.0  Female    Port Tracistad           Alaska          Yes
104993        42.0  Female     West Annaport          Florida          Yes
104994        53.0  Female     Michelleburgh     South Dakota           No
104995        74.0   Other      West Anthony         Oklahoma          Yes
104997        51.0  Female  Lake Lisachester         Nebraska          Yes

       visitedlastmonth paymentmethod preferreddoctor diseasediagnosed  \
104992               No     Insurance       Dr. Brown             Cold
104993               No          Cash     Dr. Johnson         Covid-19
104994               No          Card    Dr. Williams              Flu
104995               No          Card    Dr. Williams         Covid-19
104997              Yes     Insurance    Dr. Williams          Allergy

       medicationprescribed  ... heightincm  weightinkg  paymentdue  \
104992                Med_A  ...      178.0        66.0  462.565671
104993                Med_D  ...      171.0        78.0  131.356326
104994                Med_B  ...      172.0        75.0  488.031604
104995                Med_E  ...      169.0        61.0  309.164446
104997                Med_D  ...      179.0        71.0  320.830418

        lastvisitdaysago  visitdurationmins  numberoftests  prescriptioncost  \
104992             189.0               55.0            3.0         59.746318
104993             185.0               22.0            6.0        104.430167
104994             167.0               25.0            5.0         69.542286
104995             183.0               10.0            3.0         63.204788
104997             172.0               39.0            3.0         35.622420

        patientunder40  averagecardio  averagecardioval
104992           Older           84.5              76.0
104993           Older          104.5              80.0
104994           Older           88.5              68.0
104995           Older           88.5              65.0
104997           Older          103.5              89.0

[5 rows x 23 columns]

In [110]:
diseased_diagnoses = hcdata['diseasediagnosed'].value_counts()
print(diseased_diagnoses)

Cold        7598
None        7528
Flu         7510
Covid-19    7495
Allergy     7463
Name: diseasediagnosed, dtype: int64

In [111]:
null_patient_age = hcdata['patientage'].isnull()
print(null_patient_age.sum())

0

In [108]:
payment_method = hcdata['paymentmethod'].describe()
print(payment_method)

count     37594
unique        3
top        Cash
freq      12610
Name: paymentmethod, dtype: object

In [112]:
hcdata

,patientage,gender,cityofresidence,stateofresidence,hasinsurance,visitedlastmonth,paymentmethod,preferreddoctor,diseasediagnosed,medicationprescribed,...,heightincm,weightinkg,paymentdue,lastvisitdaysago,visitdurationmins,numberoftests,prescriptioncost,patientunder40,averagecardio,averagecardioval
0,45.0,Other,West Brian,Kentucky,Yes,Yes,Insurance,Dr. Williams,Flu,Med_E,...,183.0,70.0,65.457216,193.0,92.0,5.0,15.717517,Older,88.5,66.0
4,48.0,Female,Birdmouth,Montana,No,No,Insurance,Dr. Brown,None,Med_C,...,186.0,87.0,264.214737,188.0,113.0,3.0,77.483113,Older,91.0,93.0
7,52.0,Male,Vanessaburgh,Connecticut,Yes,Yes,Insurance,Dr. Williams,Flu,Med_E,...,170.0,47.0,387.085044,179.0,108.0,2.0,76.965926,Older,114.0,99.0
8,20.0,Female,West Briannabury,Montana,No,Yes,Card,Dr. Jones,Flu,Med_C,...,173.0,86.0,172.548343,174.0,91.0,2.0,142.317108,Younger,87.5,67.0
11,40.0,Female,Jonesmouth,Rhode Island,No,No,Card,Dr. Jones,Covid-19,Med_E,...,166.0,82.0,299.142676,193.0,92.0,1.0,77.715360,Older,85.5,65.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
104992,44.0,Female,Port Tracistad,Alaska,Yes,No,Insurance,Dr. Brown,Cold,Med_A,...,178.0,66.0,462.565671,189.0,55.0,3.0,59.746318,Older,84.5,76.0
104993,42.0,Female,West Annaport,Florida,Yes,No,Cash,Dr. Johnson,Covid-19,Med_D,...,171.0,78.0,131.356326,185.0,22.0,6.0,104.430167,Older,104.5,80.0
104994,53.0,Female,Michelleburgh,South Dakota,No,No,Card,Dr. Williams,Flu,Med_B,...,172.0,75.0,488.031604,167.0,25.0,5.0,69.542286,Older,88.5,68.0
104995,74.0,Other,West Anthony,Oklahoma,Yes,No,Card,Dr. Williams,Covid-19,Med_E,...,169.0,61.0,309.164446,183.0,10.0,3.0,63.204788,Older,88.5,65.0
104997,51.0,Female,Lake Lisachester,Nebraska,Yes,Yes,Insurance,Dr. Williams,Allergy,Med_D,...,179.0,71.0,320.830418,172.0,39.0,3.0,35.622420,Older,103.5,89.0

In [113]:
# Remove all white space from the column names
hcdata.columns = hcdata.columns.str.strip()

# Replace all special characters with underscores
hcdata.columns = hcdata.columns.str.replace("[^\w_]", "_")

# Convert all characters to lowercase
hcdata.columns = hcdata.columns.str.lower()

print(hcdata)

        patientage  gender   cityofresidence stateofresidence hasinsurance  \
0             45.0   Other        West Brian         Kentucky          Yes
4             48.0  Female         Birdmouth          Montana           No
7             52.0    Male      Vanessaburgh      Connecticut          Yes
8             20.0  Female  West Briannabury          Montana           No
11            40.0  Female        Jonesmouth     Rhode Island           No
...            ...     ...               ...              ...          ...
104992        44.0  Female    Port Tracistad           Alaska          Yes
104993        42.0  Female     West Annaport          Florida          Yes
104994        53.0  Female     Michelleburgh     South Dakota           No
104995        74.0   Other      West Anthony         Oklahoma          Yes
104997        51.0  Female  Lake Lisachester         Nebraska          Yes

       visitedlastmonth paymentmethod preferreddoctor diseasediagnosed  \
0                   Yes     Insurance    Dr. Williams              Flu
4                    No     Insurance       Dr. Brown             None
7                   Yes     Insurance    Dr. Williams              Flu
8                   Yes          Card       Dr. Jones              Flu
11                   No          Card       Dr. Jones         Covid-19
...                 ...           ...             ...              ...
104992               No     Insurance       Dr. Brown             Cold
104993               No          Cash     Dr. Johnson         Covid-19
104994               No          Card    Dr. Williams              Flu
104995               No          Card    Dr. Williams         Covid-19
104997              Yes     Insurance    Dr. Williams          Allergy

       medicationprescribed  ... heightincm  weightinkg  paymentdue  \
0                     Med_E  ...      183.0        70.0   65.457216
4                     Med_C  ...      186.0        87.0  264.214737
7                     Med_E  ...      170.0        47.0  387.085044
8                     Med_C  ...      173.0        86.0  172.548343
11                    Med_E  ...      166.0        82.0  299.142676
...                     ...  ...        ...         ...         ...
104992                Med_A  ...      178.0        66.0  462.565671
104993                Med_D  ...      171.0        78.0  131.356326
104994                Med_B  ...      172.0        75.0  488.031604
104995                Med_E  ...      169.0        61.0  309.164446
104997                Med_D  ...      179.0        71.0  320.830418

        lastvisitdaysago  visitdurationmins  numberoftests  prescriptioncost  \
0                  193.0               92.0            5.0         15.717517
4                  188.0              113.0            3.0         77.483113
7                  179.0              108.0            2.0         76.965926
8                  174.0               91.0            2.0        142.317108
11                 193.0               92.0            1.0         77.715360
...                  ...                ...            ...               ...
104992             189.0               55.0            3.0         59.746318
104993             185.0               22.0            6.0        104.430167
104994             167.0               25.0            5.0         69.542286
104995             183.0               10.0            3.0         63.204788
104997             172.0               39.0            3.0         35.622420

        patientunder40  averagecardio  averagecardioval
0                Older           88.5              66.0
4                Older           91.0              93.0
7                Older          114.0              99.0
8              Younger           87.5              67.0
11               Older           85.5              65.0
...                ...            ...               ...
104992           Older           84.5              76.0
104993           Older          104.5              80.0
104994           Older           88.5              68.0
104995           Older           88.5              65.0
104997           Older          103.5              89.0

[37594 rows x 23 columns]

<ipython-input-113-2f66875ba2d2>:5: FutureWarning: The default value of regex will change from True to False in a future version.
  hcdata.columns = hcdata.columns.str.replace("[^\w_]", "_")

In [118]:
#Pandas
pd_hcdata = pd.read_csv('https://raw.githubusercontent.com/amnasyed1/datasci_2_manipulation/main/dataset/healthcare_data_cleaning.csv')
start_time_pd = time.time()
end_time_pd = time.time()
load_time_pd = end_time_pd - start_time_pd
print(f'load time using pandas : {load_time_pd} seconds')

load time using pandas : 5.316734313964844e-05 seconds

In [116]:
#Polars
pl_hcdata = pl.read_csv('https://raw.githubusercontent.com/amnasyed1/datasci_2_manipulation/main/dataset/healthcare_data_cleaning.csv')
start_time_pl = time.time ()
end_time_pl = time.time()
load_time_pl = end_time_pl - start_time_pl
print(f'load time using polars: {load_time_pl} seconds')

load time using polars: 3.790855407714844e-05 seconds

### Observations
  - The loading time for pandas is higher, therefore, Pandas loaded the CSV file slower than Polars.
  - That indicates Polars loaded the CSV file faster.